Czech translation
aatishb/maskmath pull request #36
Opened 2020-09-23 12:47 UTC by progproc

First draft of the Czech translation. Will amend if my proofreaders find anything. 
I checked this and it works on desktop and in a phone web browser.

Some labels were longer than in English but I think it's better to have it longer rather than simplify too much.

Notes:
The headline means **"The surprising efficacy of surgical face masks and respirators"**

I use the translation of "roušky a respirátory" (surgical face masks and respirators) or "ochrana obličeje" (face protection), since "face mask" does not have an easy translation that would make sense in the context of this essay.

2020-09-24 09:57 UTC, progproc commented
I added some more corrections from my Twitter followers.

2020-09-26 23:13 UTC, aatishb commented
Thanks! I'll work on bringing this in sync with the live branch in the next few days. Once I'm done will let you know if any steps remain.

2020-09-27 22:50 UTC, aatishb requested changes
Hi @progproc. Thanks for all your work on this, it looks great. I brought this up to date with the live version. The only thing remaining is one small translation, you can do this by committing the change to your branch as before, and it should automatically appear here. Or just let me know the translation and I can swap it in. Thanks!

2020-09-27 22:50 UTC, aatishb commented on index-cs.html
> +        '% Infected'
@progproc we added a new line of code here so that this hover text can be translated. Could you please translate this phrase?

2020-09-27 22:52 UTC, aatishb commented
Tagging #4

2020-09-28 00:10 UTC, progproc commented
I am only starting with github so not sure what to do. I guess this would
be simpler:

Translation:
Infected = Infikovaných

Thanks

On Mon, Sep 28, 2020 at 12:52 AM Aatish Bhatia <notifications@github.com>
wrote:

> Tagging #4 <https://github.com/aatishb/maskmath/issues/4>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aatishb/maskmath/pull/36#issuecomment-699698501>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALMKGZOR7N3JGBNOMTWEFPTSH662XANCNFSM4RW7YNPA>
> .
>

2020-09-28 00:10 UTC, progproc commented
People are definitely liking the essay. Thanks again!

On Mon, Sep 28, 2020 at 2:09 AM Pavel Kasík <kasikp@gmail.com> wrote:

> I am only starting with github so not sure what to do. I guess this would
> be simpler:
>
> Translation:
> Infected = Infikovaných
>
> Thanks
>
> On Mon, Sep 28, 2020 at 12:52 AM Aatish Bhatia <notifications@github.com>
> wrote:
>
>> Tagging #4 <https://github.com/aatishb/maskmath/issues/4>
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/aatishb/maskmath/pull/36#issuecomment-699698501>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ALMKGZOR7N3JGBNOMTWEFPTSH662XANCNFSM4RW7YNPA>
>> .
>>
>

2020-09-29 15:32 UTC, aatishb approved these changes

2020-09-29 15:33 UTC, merged

2020-09-29 15:34 UTC, aatishb commented
@progproc it's live! Thanks for all your efforts on this. Glad to see it reach a wider audience.

2020-09-29 15:34 UTC, aatishb commented
@all-contributors add @progproc for translation